version: '3.3'
services:
  stdm-db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'stdm-db'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'mysql'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - stdm-db:/var/lib/mysql
volumes:
  stdm-db: