version: '3.3'
services:
  stdm-db:
    image: mysql:5.7
    container_name: stdm-db
    restart: always
    tty: true
    environment:
      MYSQL_DATABASE: 'stdm-db'
      MYSQL_USER: 'mysql'
      MYSQL_PASSWORD: 'mysql'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - stdm-db:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    tty: true
    links:
      - stdm-db
    environment:
      PMA_HOST: stdm-db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
volumes:
  stdm-db:
