INSERT INTO `country` (`iso`, `name`, `flagUrl`) VALUES
('AF', 'Afghanistan', 'thispersondoesnotexist.com/image'),
('AX', 'Aland Islands', 'thispersondoesnotexist.com/image'),
('AL', 'Albania', 'thispersondoesnotexist.com/image'),
('DZ', 'Algeria', 'thispersondoesnotexist.com/image'),
('AS', 'American Samoa', 'thispersondoesnotexist.com/image'),
('AD', 'Andorra', 'thispersondoesnotexist.com/image'),
('AO', 'Angola', 'thispersondoesnotexist.com/image'),
('AI', 'Anguilla', 'thispersondoesnotexist.com/image'),
('AQ', 'Antarctica', 'thispersondoesnotexist.com/image'),
('AG', 'Antigua and Barbuda', 'thispersondoesnotexist.com/image'),
('AR', 'Argentina', 'thispersondoesnotexist.com/image'),
('AM', 'Armenia', 'thispersondoesnotexist.com/image'),
('AW', 'Aruba', 'thispersondoesnotexist.com/image'),
('AU', 'Australia', 'thispersondoesnotexist.com/image'),
('AT', 'Austria', 'thispersondoesnotexist.com/image'),
('AZ', 'Azerbaijan', 'thispersondoesnotexist.com/image'),
('BS', 'Bahamas', 'thispersondoesnotexist.com/image'),
('BH', 'Bahrain', 'thispersondoesnotexist.com/image'),
('BD', 'Bangladesh', 'thispersondoesnotexist.com/image'),
('BB', 'Barbados', 'thispersondoesnotexist.com/image'),
('BY', 'Belarus', 'thispersondoesnotexist.com/image'),
('BE', 'Belgium', 'thispersondoesnotexist.com/image'),
('BZ', 'Belize', 'thispersondoesnotexist.com/image'),
('BJ', 'Benin', 'thispersondoesnotexist.com/image'),
('BM', 'Bermuda', 'thispersondoesnotexist.com/image'),
('BT', 'Bhutan', 'thispersondoesnotexist.com/image'),
('BO', 'Bolivia', 'thispersondoesnotexist.com/image'),
('BQ', 'Bonaire, Sint Eustatius and Saba', 'thispersondoesnotexist.com/image'),
('BA', 'Bosnia and Herzegovina', 'thispersondoesnotexist.com/image'),
('BW', 'Botswana', 'thispersondoesnotexist.com/image'),
('BV', 'Bouvet Island', 'thispersondoesnotexist.com/image'),
('BR', 'Brazil', 'thispersondoesnotexist.com/image'),
('IO', 'British Indian Ocean Territory', 'thispersondoesnotexist.com/image'),
('BN', 'Brunei Darussalam', 'thispersondoesnotexist.com/image'),
('BG', 'Bulgaria', 'thispersondoesnotexist.com/image'),
('BF', 'Burkina Faso', 'thispersondoesnotexist.com/image'),
('BI', 'Burundi', 'thispersondoesnotexist.com/image'),
('KH', 'Cambodia', 'thispersondoesnotexist.com/image'),
('CM', 'Cameroon', 'thispersondoesnotexist.com/image'),
('CA', 'Canada', 'thispersondoesnotexist.com/image'),
('CV', 'Cape Verde', 'thispersondoesnotexist.com/image'),
('KY', 'Cayman Islands', 'thispersondoesnotexist.com/image'),
('CF', 'Central African Republic', 'thispersondoesnotexist.com/image'),
('TD', 'Chad', 'thispersondoesnotexist.com/image'),
('CL', 'Chile', 'thispersondoesnotexist.com/image'),
('CN', 'China', 'thispersondoesnotexist.com/image'),
('CX', 'Christmas Island', 'thispersondoesnotexist.com/image'),
('CC', 'Cocos (Keeling) Islands', 'thispersondoesnotexist.com/image'),
('CO', 'Colombia', 'thispersondoesnotexist.com/image'),
('KM', 'Comoros', 'thispersondoesnotexist.com/image'),
('CG', 'Congo', 'thispersondoesnotexist.com/image'),
('CD', 'Congo, Democratic Republic of the Congo', 'thispersondoesnotexist.com/image'),
('CK', 'Cook Islands', 'thispersondoesnotexist.com/image'),
('CR', 'Costa Rica', 'thispersondoesnotexist.com/image'),
('CI', 'Cote D\'Ivoire', 'thispersondoesnotexist.com/image'),
('HR', 'Croatia', 'thispersondoesnotexist.com/image'),
('CU', 'Cuba', 'thispersondoesnotexist.com/image'),
('CW', 'Curacao', 'thispersondoesnotexist.com/image'),
('CY', 'Cyprus', 'thispersondoesnotexist.com/image'),
('CZ', 'Czech Republic', 'thispersondoesnotexist.com/image'),
('DK', 'Denmark', 'thispersondoesnotexist.com/image'),
('DJ', 'Djibouti', 'thispersondoesnotexist.com/image'),
('DM', 'Dominica', 'thispersondoesnotexist.com/image'),
('DO', 'Dominican Republic', 'thispersondoesnotexist.com/image'),
('EC', 'Ecuador', 'thispersondoesnotexist.com/image'),
('EG', 'Egypt', 'thispersondoesnotexist.com/image'),
('SV', 'El Salvador', 'thispersondoesnotexist.com/image'),
('GQ', 'Equatorial Guinea', 'thispersondoesnotexist.com/image'),
('ER', 'Eritrea', 'thispersondoesnotexist.com/image'),
('EE', 'Estonia', 'thispersondoesnotexist.com/image'),
('ET', 'Ethiopia', 'thispersondoesnotexist.com/image'),
('FK', 'Falkland Islands (Malvinas)', 'thispersondoesnotexist.com/image'),
('FO', 'Faroe Islands', 'thispersondoesnotexist.com/image'),
('FJ', 'Fiji', 'thispersondoesnotexist.com/image'),
('FI', 'Finland', 'thispersondoesnotexist.com/image'),
('FR', 'France', 'thispersondoesnotexist.com/image'),
('GF', 'French Guiana', 'thispersondoesnotexist.com/image'),
('PF', 'French Polynesia', 'thispersondoesnotexist.com/image'),
('TF', 'French Southern Territories', 'thispersondoesnotexist.com/image'),
('GA', 'Gabon', 'thispersondoesnotexist.com/image'),
('GM', 'Gambia', 'thispersondoesnotexist.com/image'),
('GE', 'Georgia', 'thispersondoesnotexist.com/image'),
('DE', 'Germany', 'thispersondoesnotexist.com/image'),
('GH', 'Ghana', 'thispersondoesnotexist.com/image'),
('GI', 'Gibraltar', 'thispersondoesnotexist.com/image'),
('GR', 'Greece', 'thispersondoesnotexist.com/image'),
('GL', 'Greenland', 'thispersondoesnotexist.com/image'),
('GD', 'Grenada', 'thispersondoesnotexist.com/image'),
('GP', 'Guadeloupe', 'thispersondoesnotexist.com/image'),
('GU', 'Guam', 'thispersondoesnotexist.com/image'),
('GT', 'Guatemala', 'thispersondoesnotexist.com/image'),
('GG', 'Guernsey', 'thispersondoesnotexist.com/image'),
('GN', 'Guinea', 'thispersondoesnotexist.com/image'),
('GW', 'Guinea-Bissau', 'thispersondoesnotexist.com/image'),
('GY', 'Guyana', 'thispersondoesnotexist.com/image'),
('HT', 'Haiti', 'thispersondoesnotexist.com/image'),
('HM', 'Heard Island and Mcdonald Islands', 'thispersondoesnotexist.com/image'),
('VA', 'Holy See (Vatican City State)', 'thispersondoesnotexist.com/image'),
('HN', 'Honduras', 'thispersondoesnotexist.com/image'),
('HK', 'Hong Kong', 'thispersondoesnotexist.com/image'),
('HU', 'Hungary', 'thispersondoesnotexist.com/image'),
('IS', 'Iceland', 'thispersondoesnotexist.com/image'),
('IN', 'India', 'thispersondoesnotexist.com/image'),
('ID', 'Indonesia', 'thispersondoesnotexist.com/image'),
('IR', 'Iran, Islamic Republic of', 'thispersondoesnotexist.com/image'),
('IQ', 'Iraq', 'thispersondoesnotexist.com/image'),
('IE', 'Ireland', 'thispersondoesnotexist.com/image'),
('IM', 'Isle of Man', 'thispersondoesnotexist.com/image'),
('IL', 'Israel', 'thispersondoesnotexist.com/image'),
('IT', 'Italy', 'thispersondoesnotexist.com/image'),
('JM', 'Jamaica', 'thispersondoesnotexist.com/image'),
('JP', 'Japan', 'thispersondoesnotexist.com/image'),
('JE', 'Jersey', 'thispersondoesnotexist.com/image'),
('JO', 'Jordan', 'thispersondoesnotexist.com/image'),
('KZ', 'Kazakhstan', 'thispersondoesnotexist.com/image'),
('KE', 'Kenya', 'thispersondoesnotexist.com/image'),
('KI', 'Kiribati', 'thispersondoesnotexist.com/image'),
('KP', 'Korea, Democratic People\'s Republic of', 'thispersondoesnotexist.com/image'),
('KR', 'Korea, Republic of', 'thispersondoesnotexist.com/image'),
('XK', 'Kosovo', 'thispersondoesnotexist.com/image'),
('KW', 'Kuwait', 'thispersondoesnotexist.com/image'),
('KG', 'Kyrgyzstan', 'thispersondoesnotexist.com/image'),
('LA', 'Lao People\'s Democratic Republic', 'thispersondoesnotexist.com/image'),
('LV', 'Latvia', 'thispersondoesnotexist.com/image'),
('LB', 'Lebanon', 'thispersondoesnotexist.com/image'),
('LS', 'Lesotho', 'thispersondoesnotexist.com/image'),
('LR', 'Liberia', 'thispersondoesnotexist.com/image'),
('LY', 'Libyan Arab Jamahiriya', 'thispersondoesnotexist.com/image'),
('LI', 'Liechtenstein', 'thispersondoesnotexist.com/image'),
('LT', 'Lithuania', 'thispersondoesnotexist.com/image'),
('LU', 'Luxembourg', 'thispersondoesnotexist.com/image'),
('MO', 'Macao', 'thispersondoesnotexist.com/image'),
('MK', 'Macedonia, the Former Yugoslav Republic of', 'thispersondoesnotexist.com/image'),
('MG', 'Madagascar', 'thispersondoesnotexist.com/image'),
('MW', 'Malawi', 'thispersondoesnotexist.com/image'),
('MY', 'Malaysia', 'thispersondoesnotexist.com/image'),
('MV', 'Maldives', 'thispersondoesnotexist.com/image'),
('ML', 'Mali', 'thispersondoesnotexist.com/image'),
('MT', 'Malta', 'thispersondoesnotexist.com/image'),
('MH', 'Marshall Islands', 'thispersondoesnotexist.com/image'),
('MQ', 'Martinique', 'thispersondoesnotexist.com/image'),
('MR', 'Mauritania', 'thispersondoesnotexist.com/image'),
('MU', 'Mauritius', 'thispersondoesnotexist.com/image'),
('YT', 'Mayotte', 'thispersondoesnotexist.com/image'),
('MX', 'Mexico', 'thispersondoesnotexist.com/image'),
('FM', 'Micronesia, Federated States of', 'thispersondoesnotexist.com/image'),
('MD', 'Moldova, Republic of', 'thispersondoesnotexist.com/image'),
('MC', 'Monaco', 'thispersondoesnotexist.com/image'),
('MN', 'Mongolia', 'thispersondoesnotexist.com/image'),
('ME', 'Montenegro', 'thispersondoesnotexist.com/image'),
('MS', 'Montserrat', 'thispersondoesnotexist.com/image'),
('MA', 'Morocco', 'thispersondoesnotexist.com/image'),
('MZ', 'Mozambique', 'thispersondoesnotexist.com/image'),
('MM', 'Myanmar', 'thispersondoesnotexist.com/image'),
('NA', 'Namibia', 'thispersondoesnotexist.com/image'),
('NR', 'Nauru', 'thispersondoesnotexist.com/image'),
('NP', 'Nepal', 'thispersondoesnotexist.com/image'),
('NL', 'Netherlands', 'thispersondoesnotexist.com/image'),
('AN', 'Netherlands Antilles', 'thispersondoesnotexist.com/image'),
('NC', 'New Caledonia', 'thispersondoesnotexist.com/image'),
('NZ', 'New Zealand', 'thispersondoesnotexist.com/image'),
('NI', 'Nicaragua', 'thispersondoesnotexist.com/image'),
('NE', 'Niger', 'thispersondoesnotexist.com/image'),
('NG', 'Nigeria', 'thispersondoesnotexist.com/image'),
('NU', 'Niue', 'thispersondoesnotexist.com/image'),
('NF', 'Norfolk Island', 'thispersondoesnotexist.com/image'),
('MP', 'Northern Mariana Islands', 'thispersondoesnotexist.com/image'),
('NO', 'Norway', 'thispersondoesnotexist.com/image'),
('OM', 'Oman', 'thispersondoesnotexist.com/image'),
('PK', 'Pakistan', 'thispersondoesnotexist.com/image'),
('PW', 'Palau', 'thispersondoesnotexist.com/image'),
('PS', 'Palestinian Territory, Occupied', 'thispersondoesnotexist.com/image'),
('PA', 'Panama', 'thispersondoesnotexist.com/image'),
('PG', 'Papua New Guinea', 'thispersondoesnotexist.com/image'),
('PY', 'Paraguay', 'thispersondoesnotexist.com/image'),
('PE', 'Peru', 'thispersondoesnotexist.com/image'),
('PH', 'Philippines', 'thispersondoesnotexist.com/image'),
('PN', 'Pitcairn', 'thispersondoesnotexist.com/image'),
('PL', 'Poland', 'thispersondoesnotexist.com/image'),
('PT', 'Portugal', 'thispersondoesnotexist.com/image'),
('PR', 'Puerto Rico', 'thispersondoesnotexist.com/image'),
('QA', 'Qatar', 'thispersondoesnotexist.com/image'),
('RE', 'Reunion', 'thispersondoesnotexist.com/image'),
('RO', 'Romania', 'thispersondoesnotexist.com/image'),
('RU', 'Russian Federation', 'thispersondoesnotexist.com/image'),
('RW', 'Rwanda', 'thispersondoesnotexist.com/image'),
('BL', 'Saint Barthelemy', 'thispersondoesnotexist.com/image'),
('SH', 'Saint Helena', 'thispersondoesnotexist.com/image'),
('KN', 'Saint Kitts and Nevis', 'thispersondoesnotexist.com/image'),
('LC', 'Saint Lucia', 'thispersondoesnotexist.com/image'),
('MF', 'Saint Martin', 'thispersondoesnotexist.com/image'),
('PM', 'Saint Pierre and Miquelon', 'thispersondoesnotexist.com/image'),
('VC', 'Saint Vincent and the Grenadines', 'thispersondoesnotexist.com/image'),
('WS', 'Samoa', 'thispersondoesnotexist.com/image'),
('SM', 'San Marino', 'thispersondoesnotexist.com/image'),
('ST', 'Sao Tome and Principe', 'thispersondoesnotexist.com/image'),
('SA', 'Saudi Arabia', 'thispersondoesnotexist.com/image'),
('SN', 'Senegal', 'thispersondoesnotexist.com/image'),
('RS', 'Serbia', 'thispersondoesnotexist.com/image'),
('CS', 'Serbia and Montenegro', 'thispersondoesnotexist.com/image'),
('SC', 'Seychelles', 'thispersondoesnotexist.com/image'),
('SL', 'Sierra Leone', 'thispersondoesnotexist.com/image'),
('SG', 'Singapore', 'thispersondoesnotexist.com/image'),
('SX', 'Sint Maarten', 'thispersondoesnotexist.com/image'),
('SK', 'Slovakia', 'thispersondoesnotexist.com/image'),
('SI', 'Slovenia', 'thispersondoesnotexist.com/image'),
('SB', 'Solomon Islands', 'thispersondoesnotexist.com/image'),
('SO', 'Somalia', 'thispersondoesnotexist.com/image'),
('ZA', 'South Africa', 'thispersondoesnotexist.com/image'),
('GS', 'South Georgia and the South Sandwich Islands', 'thispersondoesnotexist.com/image'),
('SS', 'South Sudan', 'thispersondoesnotexist.com/image'),
('ES', 'Spain', 'thispersondoesnotexist.com/image'),
('LK', 'Sri Lanka', 'thispersondoesnotexist.com/image'),
('SD', 'Sudan', 'thispersondoesnotexist.com/image'),
('SR', 'Suriname', 'thispersondoesnotexist.com/image'),
('SJ', 'Svalbard and Jan Mayen', 'thispersondoesnotexist.com/image'),
('SZ', 'Swaziland', 'thispersondoesnotexist.com/image'),
('SE', 'Sweden', 'thispersondoesnotexist.com/image'),
('CH', 'Switzerland', 'thispersondoesnotexist.com/image'),
('SY', 'Syrian Arab Republic', 'thispersondoesnotexist.com/image'),
('TW', 'Taiwan, Province of China', 'thispersondoesnotexist.com/image'),
('TJ', 'Tajikistan', 'thispersondoesnotexist.com/image'),
('TZ', 'Tanzania, United Republic of', 'thispersondoesnotexist.com/image'),
('TH', 'Thailand', 'thispersondoesnotexist.com/image'),
('TL', 'Timor-Leste', 'thispersondoesnotexist.com/image'),
('TG', 'Togo', 'thispersondoesnotexist.com/image'),
('TK', 'Tokelau', 'thispersondoesnotexist.com/image'),
('TO', 'Tonga', 'thispersondoesnotexist.com/image'),
('TT', 'Trinidad and Tobago', 'thispersondoesnotexist.com/image'),
('TN', 'Tunisia', 'thispersondoesnotexist.com/image'),
('TR', 'Turkey', 'thispersondoesnotexist.com/image'),
('TM', 'Turkmenistan', 'thispersondoesnotexist.com/image'),
('TC', 'Turks and Caicos Islands', 'thispersondoesnotexist.com/image'),
('TV', 'Tuvalu', 'thispersondoesnotexist.com/image'),
('UG', 'Uganda', 'thispersondoesnotexist.com/image'),
('UA', 'Ukraine', 'thispersondoesnotexist.com/image'),
('AE', 'United Arab Emirates', 'thispersondoesnotexist.com/image'),
('GB', 'United Kingdom', 'thispersondoesnotexist.com/image'),
('US', 'United States', 'thispersondoesnotexist.com/image'),
('UM', 'United States Minor Outlying Islands', 'thispersondoesnotexist.com/image'),
('UY', 'Uruguay', 'thispersondoesnotexist.com/image'),
('UZ', 'Uzbekistan', 'thispersondoesnotexist.com/image'),
('VU', 'Vanuatu', 'thispersondoesnotexist.com/image'),
('VE', 'Venezuela', 'thispersondoesnotexist.com/image'),
('VN', 'Viet Nam', 'thispersondoesnotexist.com/image'),
('VG', 'Virgin Islands, British', 'thispersondoesnotexist.com/image'),
('VI', 'Virgin Islands, U.s.', 'thispersondoesnotexist.com/image'),
('WF', 'Wallis and Futuna', 'thispersondoesnotexist.com/image'),
('EH', 'Western Sahara', 'thispersondoesnotexist.com/image'),
('YE', 'Yemen', 'thispersondoesnotexist.com/image'),
('ZM', 'Zambia', 'thispersondoesnotexist.com/image'),
('ZW', 'Zimbabwe', 'thispersondoesnotexist.com/image');