INSERT INTO player (
    name,
    teamId,
    countryId,
    positon,
    number,
    height,
    weight,
    birthDate,
    avatarUrl
) VALUES (
        'Manuel',
        1,
        1,
        'ST',
        12,
        175,
        120,
        '1985-09-14',
        'https://thispersondoesnotexist.com/image'
    ),(
        'Manuel',
        2,
        1,
        'CM',
        12,
        190,
        95,
        '1985-07-14',
        'https://thispersondoesnotexist.com/image'
    ),(
        'Manuel',
        1,
        1,
        'CB',
        12,
        175,
        80,
        '1985-09-12',
        'https://thispersondoesnotexist.com/image'
    ),(
        'Manuel',
        1,
        4,
        'CM',
        12,
        175,
        80,
        '1985-09-04',
        'https://thispersondoesnotexist.com/image'
    ),(
        'Manuel',
        1,
        1,
        'ST',
        12,
        175,
        80,
        '1985-09-14',
        'https://thispersondoesnotexist.com/image'
    ),(
        'Manuel',
        1,
        7,
        'ST',
        12,
        175,
        80,
        '1955-09-14',
        'https://thispersondoesnotexist.com/image'
    ),(
        'Manuel',
        1,
        2,
        'ST',
        12,
        190,
        80,
        '1999-09-14',
        'https://thispersondoesnotexist.com/image'
    ),(
        'Manuel',
        1,
        1,
        'ST',
        12,
        175,
        80,
        '1985-09-14',
        'https://thispersondoesnotexist.com/image'
    ),(
        'Manuel',
        1,
        1,
        'GW',
        12,
        190,
        80,
        '1985-10-14',
        'https://thispersondoesnotexist.com/image'
    ),(
        'Manuel',
        1,
        1,
        'CB',
        12,
        175,
        120,
        '1985-09-14',
        'https://thispersondoesnotexist.com/image'
    ),(
        'Manuel',
        1,
        1,
        'ST',
        12,
        175,
        80,
        '1985-09-14',
        'https://thispersondoesnotexist.com/image'
    ),(
        'Manuel',
        1,
        1,
        'ST',
        12,
        164,
        95,
        '1985-09-14',
        'https://thispersondoesnotexist.com/image'
    ),(
        'Manuel',
        1,
        1,
        'ST',
        12,
        175,
        80,
        '1985-11-14',
        'https://thispersondoesnotexist.com/image'
    ),(
        'Manuel',
        1,
        1,
        'ST',
        12,
        175,
        95,
        '1985-09-14',
        'https://thispersondoesnotexist.com/image'
    ),(
        'Manuel',
        1,
        1,
        'ST',
        12,
        175,
        120,
        '1985-09-23',
        'https://thispersondoesnotexist.com/image'
    ),(
        'Manuel',
        1,
        1,
        'ST',
        12,
        164,
        120,
        '1985-09-24',
        'https://thispersondoesnotexist.com/image'
    ),(
        'Manuel Dunkel',
        1,
        1,
        'CB',
        12,
        164,
        95,
        '1965-09-14',
        'https://thispersondoesnotexist.com/image'
    ),(
        'Manuel',
        2,
        1,
        'GW',
        12,
        175,
        80,
        '1984-09-14',
        'https://thispersondoesnotexist.com/image'
    ),(
        'Manuel',
        2,
        1,
        'CB',
        12,
        175,
        80,
        '1985-09-14',
        'https://thispersondoesnotexist.com/image'
    ),(
        'Manuel',
        2,
        1,
        'ST',
        12,
        175,
        80,
        '1985-11-14',
        'https://thispersondoesnotexist.com/image'
    ),(
        'Manuel',
        2,
        1,
        'ST',
        12,
        175,
        80,
        '1985-09-14',
        'https://thispersondoesnotexist.com/image'
    ),(
        'Manuel',
        2,
        1,
        'CB',
        12,
        175,
        80,
        '1985-09-14',
        'https://thispersondoesnotexist.com/image'
    );